spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@jsdt04.cbhhznrharey.ap-northeast-2.rds.amazonaws.com:1521:ORCL
    username: incjsdt04
    password: increpasjsdt04
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
  type-aliases-package: xyz.thedyps.project.springboot.goods
  mapper-locations: classpath:mapper/**/*.xml